---
- name: Install pyexporter
  hosts: all
  become: true
  tasks:
    - name: Ensure Python and venv are installed
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
        state: present
        update_cache: true

    - name: Install package
      ansible.builtin.pip:
        name: py-exporter-template
      args:
        virtualenv: /opt/pyexporter/venv
        virtualenv_command: "python3 -m venv"

    - name: Create a systemd service file
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/pyexporter.service
        mode: "0644"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable the service
      ansible.builtin.systemd:
        name: pyexporter
        enabled: true
        state: started
