---
log:
  level: info
web:
  port: 9123
  addr: "0.0.0.0"
  tls:
    cert: null
    key: null
    protocol: "TLS_CLIENT"
    mtls:
      enabled: false
      cert: null
      key: null
collector:
  disable_created_series: false
  default:
    gc: true
    platform: true
    process: true
