{
 "title": "pyexporter",
 "tags": [ "pyexporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(pyexporter_version_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pyexporter_version_info{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "stat",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "stat",
     "description": "Number of open file descriptors.",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max FDs",
     "type": "stat",
     "description": "Maximum number of open file descriptors.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC collected objects rate",
     "type": "timeseries",
     "description": "Objects collected during gc",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "gen{{generation}}"
      }
     ]
    },
    {
     "title": "GC uncollectable objects rate",
     "type": "timeseries",
     "description": "Uncollectable objects found during GC",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(python_gc_objects_uncollectable_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "gen{{generation}}"
      }
     ]
    },
    {
     "title": "GC collection rate per generation",
     "type": "timeseries",
     "description": "Number of times this generation was collected",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(python_gc_collections_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "gen{{generation}}"
      }
     ]
    },
    {
     "title": "Python",
     "type": "table",
     "description": "Python platform information",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}