---
name: pyexporter
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

  vector:
    image: timberio/vector:latest-debian
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - vector_data:/var/lib/vector
    ports:
      - "127.0.0.1:8686:8686"
    command: ["--config", "/etc/vector/vector.yaml"]

  pyexporter:
    image: weastur/py-exporter:latest
    container_name: pyexporter
    volumes:
      - ../config.yml:/app/config.yml
    depends_on:
      - vector
      - prometheus
    ports:
      - "127.0.0.1:9123:9123"

volumes:
  grafana_data:
  vector_data:
  prometheus_data:
